# Milestone 7.4
linux:
  hosts:
  children:
    ubuntu:
      hosts:
        10.0.5.78:
          hostname: ubuntu-1
          lan_ip: 10.0.5.30
        10.0.5.79:
          hostname: ubuntu-2
          lan_ip: 10.0.5.31
      vars:
        device: ens160

  vars:
    public_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDT4WROAHYH+GZafkUxwV6WZdsCPZcoNdGBMe7GwrENCebnrbZrm9EGD1VEoPoKkuRkwhAw4xh+2VywydBmLotnbbN4LMxzgnX24aX6ilaXE1rhtbZT7vjZ+kBXl7j8N4p4zn8aTwIGmnHn7UlBPZpxZGzxQ8FQLEgyBkPnYqWuxMLgZpx4mP8/mKJvBAlIZxAPK3q7ZnjY2zolA1qRbsdDgIz06JGBx+o2rT5F/CUDx+mEJiVYtyVmWnZ+L8fzq5i4suoXFQlnTHT87XwPoZRlE/48QTnio5AGfZooTTakXUZKsSmFzny4gm5KpujEe99UYR0va7vONfmWa1kqaAzzX17JxCKIvczrf+omRLH7FAV4OlAxXid/yyaJfP5HK3FkCijZl+tdl2htBzemEF0htEVuk6QAKSmdlQxbZLY1IQsn43T6aEIq2e57gBC1YhtDL/lGf4gD8mhhlqC/Wrl18lv5yK9Bg2ogh+CJZYVW0T0Ct5ASDCmveUiCH//slLk= jibreel@jibreel-xubuntu-wan"
    ansible_user: jibreel
    prefix: 24
    gateway: 10.0.5.2
    name_server: 10.0.5.5
    domain: blue1.local